import React from "react";
import { Lightbulb, TrendingUp, AlertTriangle, CheckCircle, Sparkles } from "lucide-react";

interface Props {
  dateFilter: string;
}

export function AIInsightsTab({ dateFilter }: Props) {
  return (
    <div className="space-y-6 h-full flex flex-col">
      <div className="flex items-center gap-3 mb-2">
        <div className="p-2 bg-indigo-500/20 rounded-xl">
          <Sparkles className="w-6 h-6 text-indigo-400" />
        </div>
        <div>
          <h2 className="text-xl font-bold text-foreground">AI Executive Summary</h2>
          <p className="text-xs text-muted-foreground">Generated by MeetPulse AI based on {dateFilter} data.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Recommendations */}
        <div className="bg-card border border-border p-6 rounded-3xl shadow-sm space-y-4">
          <div className="flex items-center gap-2 text-indigo-500 mb-4">
            <Lightbulb className="w-5 h-5" />
            <h3 className="font-bold">Key Recommendations</h3>
          </div>
          <ul className="space-y-3">
            <li className="flex gap-3 text-sm text-foreground bg-muted/30 p-3 rounded-xl border border-border">
              <span className="text-indigo-500 font-bold">1.</span>
              <span>Increase frequency of pulse checks on technical slides to maintain 90%+ understanding.</span>
            </li>
            <li className="flex gap-3 text-sm text-foreground bg-muted/30 p-3 rounded-xl border border-border">
              <span className="text-indigo-500 font-bold">2.</span>
              <span>Speaking pace spikes to 140wpm during Q&A. Consider slowing down to improve clarity scores.</span>
            </li>
            <li className="flex gap-3 text-sm text-foreground bg-muted/30 p-3 rounded-xl border border-border">
              <span className="text-indigo-500 font-bold">3.</span>
              <span>Engagement drops 15% after the 45-minute mark. Introduce a micro-break or interactive poll.</span>
            </li>
          </ul>
        </div>

        {/* Strengths & Weaknesses */}
        <div className="space-y-6">
          <div className="bg-green-500/5 border border-green-500/20 p-5 rounded-3xl">
            <div className="flex items-center gap-2 text-green-500 mb-3">
              <CheckCircle className="w-5 h-5" />
              <h3 className="font-bold">Strong Topics (High Retention)</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              <span className="bg-green-500/10 text-green-600 dark:text-green-400 text-xs px-3 py-1.5 rounded-full font-bold">Introduction to Architecture</span>
              <span className="bg-green-500/10 text-green-600 dark:text-green-400 text-xs px-3 py-1.5 rounded-full font-bold">Basic Concepts</span>
              <span className="bg-green-500/10 text-green-600 dark:text-green-400 text-xs px-3 py-1.5 rounded-full font-bold">Use Cases</span>
            </div>
          </div>

          <div className="bg-rose-500/5 border border-rose-500/20 p-5 rounded-3xl">
            <div className="flex items-center gap-2 text-rose-500 mb-3">
              <AlertTriangle className="w-5 h-5" />
              <h3 className="font-bold">Weak Topics (Needs Review)</h3>
            </div>
            <div className="flex flex-wrap gap-2">
              <span className="bg-rose-500/10 text-rose-600 dark:text-rose-400 text-xs px-3 py-1.5 rounded-full font-bold">Advanced Derivations</span>
              <span className="bg-rose-500/10 text-rose-600 dark:text-rose-400 text-xs px-3 py-1.5 rounded-full font-bold">Performance Optimization</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
